### PR TITLE
Texture cleanup

### PR DESCRIPTION
**Pull request by Yulife**
hodrij8

### CODE REVIEW

**Comment by Amaxter** [comment]
I agree with this texture change.

**Comment by ChaosTheDude** [comment]
Thanks for the textures! They all look very nice. Will merge, but may revert the Soul texture change; just not quite the style I was going for on that one. Everything else will stay, though.

**Comment by Yulife** [comment]
D: It's actually just the stray texture from vanilla

**Comment by Yulife** [comment]
Hey @ChaosTheDude may I ask when a next curse release with the textures will be up? :)

**Comment by ChaosTheDude** [comment]
Was working on a couple other features/fixes to release alongside the texture. Just released everything now in version 1.1.0.

**Comment by Yulife** [comment]
Mhm shame the soul didn't make it in, I'll put it in Unity then :)

**Pull request merged**
